product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: "-----BEGIN CERTIFICATE-----\nMIIDbzCCAlegAwIBAgIULQilsSsYG8cEgFDlvYaQYV2kUlowDQYJKoZIhvcNAQEL\nBQAwHzELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bpdm90YWwwHhcNMTkwMjAzMDkx\nMzUxWhcNMjEwMjAzMDkxMzUxWjA2MQswCQYDVQQGEwJVUzEQMA4GA1UECgwHUGl2\nb3RhbDEVMBMGA1UEAwwMYXBpLmNvcnAuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC\nAQ8AMIIBCgKCAQEAzz5iAkFBdbZtAzYvnZ0AVVJmQ4J4lj0nrzjcqPN6es1ssD7m\n44IY2iQlzHRFYvKBy7ZBo0l4ToCXpmCyfMcCtYF27Om4v/Zt1oflchJI7W8/1d6I\n+3w4cBK2jrPX5rLom1xAP2RrrUlVs1VuiuFbDElZ4i1ixhaKgs2br2XQou3LBt/f\npzighS7ocihOOPDX1vRB+C3yOgvFBxKSYMvLmOJ9BZa4LvIxQoCitV5VxRTD4Axs\nxwCEy/guEs3Hf30Hx7NOP67XDJ4eHt4vNkR0MYn9tRJo8KObm4xzO1COKuewWUi7\nAc7n8yQljYHv4SbU8TNaEjqwBeqKROmUY8ZPNwIDAQABo4GLMIGIMB0GA1UdDgQW\nBBRdZYjlHZKyMLVK/DFFdqoUST/udDAfBgNVHSMEGDAWgBQw8k2W4nrFx2td2RQQ\n+tJBQONtyDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDgYDVR0PAQH/\nBAQDAgeAMBcGA1UdEQQQMA6CDGFwaS5jb3JwLmNvbTANBgkqhkiG9w0BAQsFAAOC\nAQEAwMnP2xgilgHM+39mqrRrF0iTDAeSwj9Nf33Rkmne7vR+9GO4+a7EjQuf8fCi\na6+lnf5v17QGpy+cXT1ZqYK68h9KezAix0ITNB5QgzvUoltJfnzLKn6IcGACbTIz\n+Uk4W6GyuQH5Lckw08fnSgW1gY+ryuUxh75RkwdnJojfVK6rHhtAcm35Wph4g8FY\n1GkpwK6nmIsOBhMguq5ejD1ud6Z++2yvXuqsZzaRxbuaeDWionIHTxJfMnRGDXe4\nQdd7X+k/n1VUhS0D2lxVMymiAT39aqdHLuY+seC5Xi94MndPSnSCjuwkGyio3JT9\n4IZkLonjCVzd5fy0Yy+X5OUzUw==\n-----END CERTIFICATE-----\n"
      private_key_pem: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAzz5iAkFBdbZtAzYvnZ0AVVJmQ4J4lj0nrzjcqPN6es1ssD7m\n44IY2iQlzHRFYvKBy7ZBo0l4ToCXpmCyfMcCtYF27Om4v/Zt1oflchJI7W8/1d6I\n+3w4cBK2jrPX5rLom1xAP2RrrUlVs1VuiuFbDElZ4i1ixhaKgs2br2XQou3LBt/f\npzighS7ocihOOPDX1vRB+C3yOgvFBxKSYMvLmOJ9BZa4LvIxQoCitV5VxRTD4Axs\nxwCEy/guEs3Hf30Hx7NOP67XDJ4eHt4vNkR0MYn9tRJo8KObm4xzO1COKuewWUi7\nAc7n8yQljYHv4SbU8TNaEjqwBeqKROmUY8ZPNwIDAQABAoIBAQCM9cF0By6fAhXj\nuVdpvQAdCI7GHFgo2C/F3sc3o2QLYu4qcp5Y4IRG249aITuQsaHXDYBXsAFEY/LC\nF8NPW41cJ1LckZw39UWARa6qiAVSefjRXyuM4lEA6bmCFpEjOU09XuHUPFmA5ACG\nmfU2QVHMaZfZX0VvtqU/ktnx0y61og3pgzjTymv4L/pc/sZr0sVah593AgDn9lG8\nCYeWeiijwgNEipoHaoTWr5LO8QPAR/c13/43a3ZkBOtj/SPGztfTKneNEK1xIYQo\njgBwzTpZZtG1dMw3dfr3AWPkSHmiqqE1zE6xdisG36NapBk8li+iVoRw9OHz8A8r\nQjPJa3gBAoGBAPfLUpih8mXXz0bcK6nkuSlTRuwXHwWZUyN1/gWwRFFvnp5hpBuy\nLcyRgnmcVnckQG8oS6QbeRzj+tv2YzohZ9NjvYGeNsvXUGyY46YhtDc5u0tVuvnO\nJxRgm5F4feo9oiDuKgzHcmYqKRFVdjLLVjhFmZuj9fk+VScOx0f624ehAoGBANYb\nSuu8S+158IYg9gGgVwI9Zm6yXunQXp34NLCGnkU+47boO5QdLXFdcPdNkZgkh4+4\n5/8d9z8E3oqpsOTSfWnblc6EYpLTFMjOGSyl2g1U+aL05dnWkwbhR3g9sqzeLXab\nMQhKgXdTq6EGMyLkqHqH6aXDBwpY2NDE1APvcgfXAoGACKSw9t3/RIooksIvS7fM\ntaJQAQA1ds6IVd5RxAUH/Qc1szSYstaePlp9AJzxbyp2jOoM6WaD7PwOzglkIKz1\noCwEejb4llemWINkvXDDhoGfBNuyr+/+8PkFtCdNzRPlSdzE3rk+Rk4GLLKcct0g\n3smeuA0aEV2ZPsmHLf2UFsECgYBObF7L7AOPr3uHValmPRnBq0XKxDD5yaXujMyX\n4Cc2y+tSwsuX2/waKxTGsLXkmXTCEwN/MbWvcpQlDDTMC8F+Nb0wkNMeXoydZMhZ\nz0IIYhiyNKvAV9UwzvGDvG2m3hae/AdAtzGmyJH0ADZY0JJZl1Dgs4fvpU19YqsZ\n6enFrwKBgG/PbPCe1Cp4kZJdP9nNWwM9KV7d9dy+vyZOEG0esiPfRFaZp74MXZsh\nRwCMlrTLQO06/dFXD5IomvFdfmTUkoCHwbBNoW1S5EVOu81VqsgnBekCS3bSVCvk\nKlCF6YRuJuiDQU9ieVB1Vf0MEKbnLc6t9O+2ig7ezJWUjUjN0dA4\n-----END RSA PRIVATE KEY-----\n"
  .properties.pks_api_hostname:
    value: api.corp.com
  .properties.cloud_provider:
    value: vSphere
  .properties.cloud_provider.vsphere.vcenter_dc:
    value: RegionA01
  .properties.cloud_provider.vsphere.vcenter_ds:
    value: RegionA01-NFS01-COMP
  .properties.cloud_provider.vsphere.vcenter_ip:
    value: 192.168.110.22
  .properties.cloud_provider.vsphere.vcenter_master_creds:
    value:
      identity: administrator@vsphere.local
      password: VMware1!
  .properties.cloud_provider.vsphere.vcenter_vms:
    value: pks_vms
  .properties.network_selector:
    value: nsx  
  .properties.network_selector.nsx.nsx-t-superuser-certificate: 
    value: 
      cert_pem: "-----BEGIN CERTIFICATE-----\nMIIC1jCCAb6gAwIBAgIJAM3EWA7lDNyuMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV\nBAMME3Brcy1uc3gtdC1zdXBlcnVzZXIwHhcNMTkwMjAxMTA0MjIyWhcNMjEwMTMx\nMTA0MjIyWjAeMRwwGgYDVQQDDBNwa3MtbnN4LXQtc3VwZXJ1c2VyMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr+Yyym5Z3NiVFxUr4yt2wt6nO0ol5XPW\nVSCDSKYY5HQT3oGO9T0JvZvqbHZiSxfP+dsp+YVhIitA9fO801Co1ZYx+04H1V4M\nbk8rN/O3Onnrc0g9qgSPf4HrHbk00B0TkjvdlfIjqq+8tGZmNHmv8lWtW+3ZUZLQ\nHlz6hyBz3GT9IpldggWdk1zy48Ietr98Xehl3yimWwX+awzLaAezotWORUtBtGhx\nn2jYRpwERyfozliarybdsIdL75hZoX4OEz81W0EK+6/XhRCMTYRV+Cidu1GL3bMu\nCt/wmA0XYEMJsWLsi94SOA3ZXuhJvVxwwtEqlZOjFU0rZ9sre66UjwIDAQABoxcw\nFTATBgNVHSUEDDAKBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAl2SlHiXE\nG0eJa2XRXvlSqOSnLO1TwR99HyfUcDncH8fMJuK5Rz2jYe21EggVVjIrNwNamIe4\nOT3oYIqaXhln7ZY6rzUrK1GVxqIf9pCNKLPtXQP1HqU9EwUNm8LnJn6lfa1d/De6\n4bI8H+hNRpgVto6npS8Tan8UVDZA9kmVDGH5LzUBscp4cVMsaIEo4Dnn3MpHjjEu\nktkYZGl5PRO/ZT2vPB1pEJlPjMloSmO/1TMZOwIqJWZ9F+eQn1ogScbPbVg0fFLs\n5qCr4xUDb5TG+wQsCvQNzlIoIwoIhKlsUfVFrws3oyx+FXOBEi4PkA+5HhCDg8yT\nspbS3uvGtrpqYA==\n-----END CERTIFICATE-----\n"
      private_key_pem: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCv5jLKblnc2JUX\nFSvjK3bC3qc7SiXlc9ZVIINIphjkdBPegY71PQm9m+psdmJLF8/52yn5hWEiK0D1\n87zTUKjVljH7TgfVXgxuTys387c6eetzSD2qBI9/gesduTTQHROSO92V8iOqr7y0\nZmY0ea/yVa1b7dlRktAeXPqHIHPcZP0imV2CBZ2TXPLjwh62v3xd6GXfKKZbBf5r\nDMtoB7Oi1Y5FS0G0aHGfaNhGnARHJ+jOWJqvJt2wh0vvmFmhfg4TPzVbQQr7r9eF\nEIxNhFX4KJ27UYvdsy4K3/CYDRdgQwmxYuyL3hI4Ddle6Em9XHDC0SqVk6MVTStn\n2yt7rpSPAgMBAAECggEABWkvZsq+OOzwqSUdlH9hx9zRiCFfyQ8nKLc3UqTJXz2y\n3sVdgG3APvTs4SlDHMw+uZDkWaigtExgUzCMPnPcvbVBFFnyI74g48PLsIzutf3K\nIGG4g+JgB6wXb3KjDUPXtkfhKRupvTZqt6Huwu57WxkHnCxU4w2BGW4CxuVYqw7j\nK65cHQS3p+xxfdHj70iPUHnIaWaeh3iw35QrlQynMmZF0bJ8yagIz3G1IAEywg39\nVc7g0eqfdivRpM1IChdLbVRzjgoRE9ec1tFYb1zvLxpSql0Sckm1MXmvji2Yii52\nKGm+V4cZz53fRc1QYhFlziWuj7gC9Tbb/2zuXg6qAQKBgQDYfxLY72KAqZkoPVj1\n6vdPphP5UFSdYNoDI9agz/eW+UxRJBF3+caYD8Um9x/RbyzkevA75lDH/uog+6hp\n6+u3NCE86078kIzApfZY5QgqRn4qI5g8XdQRQN3OLAm2vkrxDGP+p9LbbKAMSKUl\nI0921fk8JaZSQ2Ao0sLMPptl1wKBgQDP/sJ7AD72vIu9KANZaKvohemlCuNINCz0\nIf/seIp+Tm3ITuatxjXapKctB5IybjwcOXnQdh0FVsjfsw7QTAFieYuSiKDmDJK/\ntKqMtwqT0Pdu7x9NjIzkgwohbF/8Fuvc2dVvwthAGbD9Yd7NUK6EJEYQSoVbVL4g\nQrEIgogACQKBgQDSUNBMcnFssFWbI82ySOqsM5if0IwCvz3LYxtz6dSKk/CxuqpF\ntR5aRqeuLNB6MtiXtV5/skSzpU5pcFCxZYD93uSTO7zl2r8Bv7hLr2N5PjX+Vcnk\nivojMLLJQTrGjqJa/UB++SX8B9CLXl8gbucZeNDAv4qNy+o0flrC8+cezQKBgCux\nQZtjDtb3/obKzAFRKqOa1dz0r4/wXe0e40sCe11TDl7ArFaex5tZcUDVUVHEtF3d\neQhgd3Iyq9nKHHeHL9dG3xn2F46b34vj4NvUa6VnhULJepLozoQGPu+Me5FSI1Pu\ncpaaoKC+hN6FW69XnoFluU4cyWzJHXNbbyLxgK45AoGBAMKQNT4QNFaVbw2bbOli\nYThRUKT22A9FVtl2J2GHTFPEPB7v1nXXD6zlZ0moEANBfsPO2omx+juHSq7yeJg1\ngSzvqHbaT3H925faYSYepNV3UyBgnQD9A9XXn74465y7qTPHsM/lxaxZaKS9KOcV\nqIw5CvodXPKso4Q5kDdTwoXf\n-----END PRIVATE KEY-----\n"
  .properties.network_selector.nsx.floating-ip-pool-ids:
    value: "c4075c3e-5391-4eba-a407-80f3f2a935b5"
  .properties.network_selector.nsx.ip-block-id:
    value: "2d675b52-f8a4-44a5-acdd-f9ce2e6fb91b"
  .properties.network_selector.nsx.nodes-ip-block-id:
    value: "96fbeec5-b784-460b-8b25-c20384218f6b"
  .properties.network_selector.nsx.cloud-config-dns:
    value: 192.168.110.10
  .properties.network_selector.nsx.nsx-t-host:
    value: 192.168.110.33
  .properties.network_selector.nsx.nsx-t-insecure:
    value: true
  .properties.network_selector.nsx.nsx-t-ca-cert:
    value: "-----BEGIN CERTIFICATE-----\nMIIDVzCCAj+gAwIBAgIJAIQV+XRxxFlMMA0GCSqGSIb3DQEBCwUAMFYxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMQswCQYDVQQHDAJDQTEMMAoGA1UE\nCgwDTlNYMRcwFQYDVQQDDA4xOTIuMTY4LjExMC4zMzAeFw0xOTAxMzAxODIzMTFa\nFw0yMDAxMzAxODIzMTFaMFYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9y\nbmlhMQswCQYDVQQHDAJDQTEMMAoGA1UECgwDTlNYMRcwFQYDVQQDDA4xOTIuMTY4\nLjExMC4zMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKVBqr+gPzZS\nyJcqravOTIgOhUK2zET2qE/EjtVpxJdkiF83RuYltsyU4z0UaNCikNPi3OfHHWDj\n0pkvASFDYVA9smBREcLyHhrEN165vZQC2owPPAXeCHKxnDe8wBQAu2oHQ9Ex3LTN\naNpY9Wjxyb0scZadIeHvKJ8chqbpGB4eAMGfu+BxHQ3wGPHEq/XMyyBtdXrdVDZV\nM6YVUxhBIn3g9JT/HUhQYQM8dG49XrfzGyydtZj88i699khg1APJBPzJUqeQVe+T\n5DBemIRVBzi5iJHiezdyscEf0uuZXEZABu40WYAJCWGI3eHe1PbRjQarnsVbGKNk\niqurZrdJ+m8CAwEAAaMoMCYwJAYDVR0RBB0wG4ITbnN4Yy0wMWEuY29ycC5sb2Nh\nbIcEwKhuITANBgkqhkiG9w0BAQsFAAOCAQEAR5rgL9Q42z5c33P5vDetLzeRA65O\nUSOBysXxOFbkvryzrXeREHAehfChwgBgp1Z78eBTjwuOuUcDDSWr4PyOqD89POwJ\n+CXRsTLsEW+nF8bqyiaT/gT7GgyzrTVNEqKj+ntmCM9IWeV9IsAV8VUB3g8n2c80\nWU11P0rCASjAwGI8jKANYH4pbAnBJGAL18lDl4L4Ws7F0CV1TPvp/3jMt/Iu5cIv\nbzRNV7hy3IXuUz+j19RkYKYNRmtPlZ7+/9lv4ES0/MRpagYjuVpfgt0ZZKkWMuxV\nGoEUhaJLllEfU7ZfBLHJggFOdSz7lVhdLZRXED7a/DDgdjHk8CqYlW2TUw==\n-----END CERTIFICATE-----\n"
  .properties.network_selector.nsx.t0-router-id:
    value: "b746adc3-1b15-4ca6-896c-180a79490183"
  .properties.network_selector.nsx.vcenter_cluster:
    value: RegionA01-K8s
  .properties.plan1_selector:
    value: Plan Active
  .properties.plan1_selector.active.allow_privileged_containers:
    value: False    
  .properties.plan1_selector.active.description:
    value: Default plan for K8s cluster
  .properties.plan1_selector.active.errand_vm_type:
    value: micro
  .properties.plan1_selector.active.master_persistent_disk_type:
    value: "10240"
  .properties.plan1_selector.active.master_vm_type:
    value: small
  .properties.plan1_selector.active.name:
    value: plan1 
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan1_selector.active.worker_vm_type:
    value: small
  .properties.plan1_selector.active.master_az_placement:
    value: ["compt_az1"]
  .properties.plan1_selector.active.worker_az_placement:
    value: ["compt_az2"]
  .properties.plan2_selector:
    value: Plan Active
  .properties.plan2_selector.active.allow_privileged_containers:
    value: False    
  .properties.plan2_selector.active.description:
    value: For Large Workloads
  .properties.plan2_selector.active.errand_vm_type:
    value: micro
  .properties.plan2_selector.active.master_persistent_disk_type:
    value: "10240"
  .properties.plan2_selector.active.master_vm_type:
    value: medium
  .properties.plan2_selector.active.name:
    value: plan2 
  .properties.plan2_selector.active.master_instances:
    value: 1
  .properties.plan2_selector.active.worker_instances:
    value: 5
  .properties.plan2_selector.active.worker_vm_type:
    value: medium
  .properties.plan2_selector.active.master_az_placement:
    value: ["compt_az1"]
  .properties.plan2_selector.active.worker_az_placement:
    value: ["compt_az2"]
  .properties.plan3_selector:
    value: Plan Inactive
  .properties.telemetry_selector:
    value: disabled   
network-properties:
  network:
    name: Opsman-Network
  other_availability_zones:
  - name: mgmt_az
  - name: compt_az1 
  - name: compt_az2
  service_network:
    name: Opsman-Network
  singleton_availability_zone:
    name: mgmt_az
errand-config:  
  pks-nsx-t-precheck:
    post-deploy-state: true
